### ISSUE TITLE
模型是不是有错误，[ERROR:0@0.017]，cv::dnn::dnn4_v20211220::ONNXImporter::parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported

### ISSUE THREAD

**Issue by kywish** [hpc203/libface-sface_detect-recognition-opencv#4]
模型是不是有错误，另不同的两个人相似度0.96以上

**Comment by kywish** [comment]
main.py，325行，默认rec_modelpath是face_detection_yunet.onnx

**Comment by 13331112522** [comment]
将rec_modelpath换成face_recognition_sface.onnx，问题依旧啊

[ERROR:0@0.041] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2516) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 243 [ 0 0 0 51 ]
[ERROR:0@0.041] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2516) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 250 [ 0 0 0 34 ]
[ERROR:0@0.042] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2516) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 257 [ 0 0 0 34 ]
[ERROR:0@0.042] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2516) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 264 [ 0 0 0 51 ]
[ERROR:0@0.042] global /Users/runner/work/opencv-python/opencv-python/opencv/modules/dnn/src/onnx/onnx_importer.cpp (2516) parseShape DNN/ONNX(Shape): dynamic 'zero' shapes are not supported, input 297 [ 0 -4 ]
